# Generated by Django 2.0.2 on 2018-08-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='layout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layouts.Layout'),
        ),
    ]
