# Generated by Django 2.0.2 on 2019-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
